### ISSUE TITLE
wp.api.collections.Posts is not a constructor

### ISSUE THREAD

**Issue by eriktdesign** [WP-API/client-js#106] opened 2016-02-29 21:29 UTC
I'm having some trouble getting my posts-fetching script to work consistently. On an initial pageload, I get a `Uncaught TypeError: wp.api.collections.Posts is not a constructor` -- however, on subsequent pageloads, it works fine. Here's some of my code:

```
jQuery( function($) {

	// Define the template to use for the excerpts
	var excerptTemplate = wp.template("excerpt");

	// Define the postsCollection object
	var postsCollection = new wp.api.collections.Posts();

	// This is the main post fetching function. 
	function fetchPosts( taxonomy = '', name = '', postOffset = 0 ) { 

		// Set some defaults
		var postsQueryArgs = {
			data: {
				'filter': {
					'orderby'		: 'date',
					'order'			: 'DESC',
					'posts_per_page': 6
				}
			}
		};
		//etc

		// Retrieve the posts and output the excerpts
		postsCollection.fetch(postsQueryArgs).done(function(data){
			outputExcerpts(data);
		});
	}

// etc
```

I'm enqueueing this file with wp_enqueue_scripts with `wp-api` and `wp-utils` as dependencies. Any idea what I'm doing wrong here? I'm guessing that `wp.api.collections.Posts` isn't finished getting set up by the time I'm trying to construct the `postsCollection` variable.

**Comment by bakken** [comment] 2016-03-02 09:31
Running into the same problem. It’s not happening on my local server, but on first load on the staging server. Disabling browser cache does not change this.
Logging the wp.api to console will show that wp.api.collections or wp.api.models has not been populated yet.
You might want to try the recent version of [client.js](https://github.com/WP-API/client-js/blob/cd4ca15cb00a0b85247f9c97210c8ee64790deb9/build/js/wp-api.js). Look at line 1317

`wp.api.loadPromise = wp.api.init();` 

Fetch your posts when wp.api.loadPromise is resolved. It looks like this could change later, so make sure to check when updating.

**Comment by MurhafSousli** [comment] 2016-03-03 03:43
Have you tried if statement?
```
if(window.wp){
// your code
}
```


-----------------------
I'm sorry, I don't want to distract, but I'm just wondering what does this line actually do
`var excerptTemplate = wp.template("excerpt");`

**Comment by kadamwhite** [comment] 2016-03-03 05:30
@MurhafSousli `wp.template` is a WordPress JavaScript helper to make it easier to use Underscore templates embedded in the page HTML; see [more information on `wp.template` in the codex](https://codex.wordpress.org/Javascript_Reference/wp.template)

**Comment by eriktdesign** [comment] 2016-03-03 18:38
So I tried what @bakken suggested and pulled in the more recent versions of the js files from the repo. Then I wrapped all my toys in this:

`$.when(wp.api.loadPromise).then( function() { // do stuff! `

This seems to do the trick -- am I doing it right? This is my first time messing around with promises...

**Comment by adamsilverstein** [comment] 2016-03-04 03:39
@eriktdesign that works... also
(with the version in master) you can use:

```js
wp.api.loadPromise.done( function() {
 ... go!
} );
```

Note:

the api is loaded asynchronously so we need to wait for it. if the schema is not localized or cached, an ajax request needs to complete to grab it before building the models/collections. if you localize the schema (this plugin does), the promise will resolve immediately.

**Comment by eriktdesign** [comment] 2016-03-04 16:44
@adamsilverstein I initially tried it that way, but I got the error "wp.api.loadPromise.done() is not a function" or something like that... Or maybe it was "wp.api doesn't exist"

**Comment by adamsilverstein** [comment] 2016-03-07 04:19
that should only happen if the api script failed to load. you have it working now?

**Comment by adamsilverstein** [comment] 2016-03-09 02:37
closing as resolved, please reopen @eriktdesign if you still have issues.

**Closed by adamsilverstein** 2016-03-09 02:37 UTC

**Comment by benoitmercusot** [comment] 2016-03-21 18:35
Hi everyone. Any workaround with the REST V2 current plugin version ?

**Comment by christill** [comment] 2016-03-22 16:45
I'm having the exact same issue. I'm able to use the API to fetch collections etc. But cannot call getCategories or anything similar.

`wp.api.loadPromise` doesn't seem to exist.

**Comment by christill** [comment] 2016-03-22 17:09
I've uploaded the Master into the plugin and wp.api.loadPromise now exists. However, now I get 
`Uncaught TypeError: b.getCategories is not a function` when I try `post.getCategories();`

**Comment by adamsilverstein** [comment] 2016-03-23 14:27
Based on your comments I don't think you have the latest version loading.

Make sure SCRIPT_DEBUG is on to have this plugin load its code over the bundles code with the WP-API plugin.

I will work on a PR to get the main repo updated.

**Comment by hyheg** [comment] 2016-05-04 11:47
I get this error using the REST V2 API and the latest master of client-js.

Even though I'm using the `wp.api.loadPromise.done` function, I get the error
`Uncaught TypeError: Cannot read property 'extend' of undefined`

I'm trying to extend `wp.api.collections.Posts` as a Backbone module. Is there any way
I could extend `wp.api.collections.Posts` before calling fetch on the extended model (eg. waiting for loadPromise).

Otherwise a pattern of actually using this library with Backbone would be greatly appreciated. Thanks!

**Comment by nathanaelphilip** [comment] 2016-05-11 00:14
Getting this error as well. Running latest version of plugin, etc.

**Comment by nathanaelphilip** [comment] 2016-05-11 00:27
```
/**
    	 * @var WP_REST_Server $wp_rest_server
    	 */
    	global $wp_rest_server;
    	if ( empty( $wp_rest_server ) ) {
    		/** This filter is documented in wp-includes/rest-api.php */
    		$wp_rest_server_class = apply_filters( 'wp_rest_server_class', 'WP_REST_Server' );
    		$wp_rest_server = new $wp_rest_server_class();
    		/** This filter is documented in wp-includes/rest-api.php */
    		do_action( 'rest_api_init', $wp_rest_server );
    	}

        $schema_request = new WP_REST_Request( 'GET', '/wp/v2' );
    	$schema_response = $wp_rest_server->dispatch( $schema_request );
    	$schema = null;
    	if ( ! $schema_response->is_error() ) {
    		$schema = $schema_response->get_data();
    	}

		$settings = array(
			'root'          => esc_url_raw( get_rest_url() ),
			'nonce'         => wp_create_nonce( 'wp_rest' ),
			'versionString' => 'wp/v2/',
            'schema' => $schema,
		);
```

Made changes in wp-content/plugins/rest-api/extras.php and it works

**Comment by hyheg** [comment] 2016-05-11 08:50
@nathanaelphilip Could you wrap that up in a pull request? I temporarily gave up on client-js because of this error.

**Comment by nathanaelphilip** [comment] 2016-05-11 11:18
@hyheg it’s already in the master branch. You can just copy what’s in the `client-js.php` file. 
It seems they haven’t put it into the WP plugin yet.

**Comment by hyheg** [comment] 2016-05-11 11:23
Cool, can we maybe put an update in the readme doc? I think that it would help noobs and get more people to try it out (eg. I think it would make it easier / faster to discover errors like these).

**Comment by nathanaelphilip** [comment] 2016-05-11 11:33
@adamsilverstein ^

**Comment by adamsilverstein** [comment] 2016-05-26 13:53
Hey @nathanaelphilip & @hyheg Thanks for the issue report here, sorry I missed the conversation. So to clarify, the issue here is that if the schema is not localized, you are getting a console error on the first load (then it works on subsequent loads)? is that right?

The library is supposed to detect if the schema is available and if not, load it asynchronously.

if you follow the pattern in the docs of starting your app once the promise in wp.api.loadPromise resolves, can you verify you were using that approach (I think you were based on your comment above). I will give this a test locally to see if I can reproduce.

**Comment by nathanaelphilip** [comment] 2016-05-26 14:16
i honestly don’t remember the exact issue, but it was like the loadPromise wasn’t resolving properly, so my code wasn’t executing when it needed to – or maybe I was just doing it wrong...

**Comment by adamsilverstein** [comment] 2016-05-26 14:47
I tested this and it works as expected. Localizing the schema is fine, however please note that the schema data is included with each request, if possible I would only pass it once, then cache in the browser.

I tested this code snippet with the schema NOT localized and clearing sessionstorage, it works as expected:

```

jQuery( document ).ready( function() {
	wp.api.loadPromise.done( function() {
		var MyExtendedPostsCollection = wp.api.collections.Posts.extend({
			'customFunction': function() {

			}
		} );
		var posts = new MyExtendedPostsCollection();
		posts.fetch().done( function() {
			console.log( posts );
		} );

	} );
} );
```
